# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# merge.py
# Created on: 2018-02-28 15:24:59.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Range_Rings = "Range Rings"
pip_buffer = "pip_buffer"
pip_range_rings_all_shp = "C:\\gina\\poker\\pip\\pip_range_rings_all.shp"

# Process: Merge
arcpy.Merge_management("'Range Rings';pip_buffer", pip_range_rings_all_shp, "Lon \"Lon\" true true false 19 Double 0 0 ,First,#,Range Rings,Lon,-1,-1,pip_buffer,Lon,-1,-1;Lat \"Lat\" true true false 19 Double 0 0 ,First,#,Range Rings,Lat,-1,-1,pip_buffer,Lat,-1,-1;ORIG_FID \"ORIG_FID\" true true false 10 Long 0 10 ,First,#,Range Rings,ORIG_FID,-1,-1,pip_buffer,ORIG_FID,-1,-1;Shape_Leng \"Shape_Leng\" true true false 19 Double 0 0 ,First,#,Range Rings,Shape_Leng,-1,-1;Shape_Area \"Shape_Area\" true true false 19 Double 0 0 ,First,#,Range Rings,Shape_Area,-1,-1;distance \"distance\" true true false 19 Double 0 0 ,First,#,Range Rings,distance,-1,-1;BUFF_DIST \"BUFF_DIST\" true true false 19 Double 0 0 ,First,#,pip_buffer,BUFF_DIST,-1,-1")

