# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# pfrr_work_20170920.py
# Created on: 2017-09-20 10:24:04.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# Generates the C:\pfrr_work\ directory.
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Folder_Location = "C:\\"
pfrr_work = Folder_Location
pfrr_predicted_impact_xy_dbf = "C:\\pfrr_work\\pfrr_predicted_impact_xy.dbf"
Output_PIP_Tbl_Lon = pfrr_predicted_impact_xy_dbf
PIP_Tbl_Lat_Lon = Output_PIP_Tbl_Lon

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = pfrr_work
arcpy.env.workspace = pfrr_work

# Process: Create Folder
arcpy.CreateFolder_management(Folder_Location, "pfrr_work")

# Process: Create Table
arcpy.CreateTable_management(pfrr_work, "pfrr_predicted_impact_xy.dbf", "", "")

# Process: Add Lon Field
arcpy.AddField_management(pfrr_predicted_impact_xy_dbf, "Lon", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Lat Field
arcpy.AddField_management(Output_PIP_Tbl_Lon, "Lat", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

