# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# pfrr_ranger_with_slurp_20170927_2.py
# Created on: 2017-09-27 14:16:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: pfrr_ranger_with_slurp_20170927_2 <Enter_Longitude__in_Decimal_Degrees_> <Enter_Latitude__in_Decimal_Degrees_> <Enter_the_3sigma_circle_Radius_and_Distance_Unit>
# Description:
# Generates the C:\pfrr_work\ directory.
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
# arcpy.ImportToolbox("E:/gina/poker/tbx/pfrr_ranger.tbx")

# Script arguments
Enter_Longitude__in_Decimal_Degrees_ = arcpy.GetParameterAsText(0)
if Enter_Longitude__in_Decimal_Degrees_ == '#' or not Enter_Longitude__in_Decimal_Degrees_:
    Enter_Longitude__in_Decimal_Degrees_ = "-145.789778" # provide a default value if unspecified

Enter_Latitude__in_Decimal_Degrees_ = arcpy.GetParameterAsText(1)
if Enter_Latitude__in_Decimal_Degrees_ == '#' or not Enter_Latitude__in_Decimal_Degrees_:
    Enter_Latitude__in_Decimal_Degrees_ = "68.005578" # provide a default value if unspecified

Enter_the_3sigma_circle_Radius_and_Distance_Unit = arcpy.GetParameterAsText(2)
if Enter_the_3sigma_circle_Radius_and_Distance_Unit == '#' or not Enter_the_3sigma_circle_Radius_and_Distance_Unit:
    Enter_the_3sigma_circle_Radius_and_Distance_Unit = "4 Miles" # provide a default value if unspecified

# Local variables:
predicted_impact_xy_dbf = "E:\\gina\\poker\\dbf\\predicted_impact_xy.dbf"
PIP_Tbl_X = predicted_impact_xy_dbf
Predicted_Impact_Point_Lat_Lon = PIP_Tbl_X
predicted_impact_xy_Layer = "predicted_impact_xy_Layer"
pip_point_shp = "E:\\gina\\poker\\pip\\pip_point.shp"
v3sigma_Circle_Output = "E:\\gina\\poker\\pip\\pip_buffer.shp"
adnr_gls_dls_merge_20170823_v1_shp = "E:\\gina\\poker\\shp\\wip\\adnr_gls_dls_merge_20170823_v1.shp"
Land_Ownership_within_3sigma_Circle = "E:\\gina\\poker\\pip\\pip_buffer_intersect_land_ownership.shp"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "E:\\gina\\poker\\pip"
arcpy.env.workspace = "E:\\gina\\poker\\pip"

# Process: Calculate Lon Field
arcpy.CalculateField_management(predicted_impact_xy_dbf, "Lon", Enter_Longitude__in_Decimal_Degrees_, "PYTHON", "")

# Process: Calculate Lat Field
arcpy.CalculateField_management(PIP_Tbl_X, "Lat", Enter_Latitude__in_Decimal_Degrees_, "PYTHON", "")

# Process: Make XY Event Layer
arcpy.MakeXYEventLayer_management(Predicted_Impact_Point_Lat_Lon, "lon", "lat", predicted_impact_xy_Layer, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;0.001;0.001;IsHighPrecision", "")

# Process: Copy Features
arcpy.CopyFeatures_management(predicted_impact_xy_Layer, pip_point_shp, "", "0", "0", "0")

# Process: Buffer
arcpy.Buffer_analysis(pip_point_shp, v3sigma_Circle_Output, Enter_the_3sigma_circle_Radius_and_Distance_Unit, "FULL", "ROUND", "NONE", "", "PLANAR")

# Process: Intersect
arcpy.Intersect_analysis("E:\\gina\\poker\\pip\\pip_buffer.shp #;E:\\gina\\poker\\shp\\wip\\adnr_gls_dls_merge_20170823_v1.shp #", Land_Ownership_within_3sigma_Circle, "ALL", "", "INPUT")

# Process: slurp_pip_dir
# arcpy.gp.toolbox = "E:/gina/poker/tbx/pfrr_ranger.tbx";
# Warning: the toolbox E:/gina/poker/tbx/pfrr_ranger.tbx DOES NOT have an alias.
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.slurp(...) with arcpy.slurp_ALIAS(...)
# arcpy.gp.slurp()

pip_dir = "E:/gina/poker/pip"
arcpy.env.workspace = pip_dir
shp_list = arcpy.ListFeatureClasses()
mxd = arcpy.mapping.MapDocument("CURRENT")
dataframe = arcpy.mapping.ListDataFrames(mxd)[0]
for shp in shp_list:
    layername = shp[:-4]
    print layername
    arcpy.MakeFeatureLayer_management(shp, layername)

layerList = arcpy.mapping.ListLayers(mxd)
for lyr in layerList:
    print "lyr: "   + str(lyr)
layer = layerList[2]
sourceLayer = layerList[5]
print "target = " + str(layer)
print "source = " + str(sourceLayer)

arcpy.mapping.UpdateLayer(dataframe, layer, sourceLayer, True)
layer.symbology.addAllValues()
layer.visible = True
arcpy.RefreshActiveView()
arcpy.RefreshTOC()

ext = layer.getExtent()
dataframe.extent = ext

