# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# shape.area_acres.py
# Created on: 2017-12-01 14:52:17.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
pip_lo_in_buffer_shp = "E:\\gina\\poker\\pip\\pip_lo_in_buffer.shp"
pip_lo_in_buffer_shp__2_ = pip_lo_in_buffer_shp

# Process: Calculate Field
arcpy.CalculateField_management(pip_lo_in_buffer_shp, "Acres", "!shape.area@acres!", "PYTHON_9.3", "")

