# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# sumlo.py
# Created on: 2017-12-04 10:20:58.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
pip_lo_in_buffer_shp = "E:\\gina\\poker\\pip\\pip_lo_in_buffer.shp"
pip_lo_in_buf_sum_dbf = "E:\\gina\\poker\\pip\\pip_lo_in_buf_sum.dbf"

# Process: Summary Statistics
arcpy.Statistics_analysis(pip_lo_in_buffer_shp, pip_lo_in_buf_sum_dbf, "Acres SUM", "OWNER")

